@extends('layouts.admin')
@section('title', $product->exists ? 'Edit Product' : 'New Product')
@section('page_title', $product->exists ? 'Edit Product' : 'New Product')
@section('content')
<form class="admin-panel admin-form" method="POST" enctype="multipart/form-data" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<div class="form-grid"><label>Arabic name<input name="name_ar" value="{{ old('name_ar', $product->name_ar) }}" required></label><label>English name<input name="name_en" value="{{ old('name_en', $product->name_en) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $product->slug) }}"></label><label>SKU <small>(optional)</small><input name="sku" value="{{ old('sku', $product->sku) }}"></label><label>Category<select name="category_id" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id) == $category->id)>{{ $category->name_en }}</option>@endforeach</select></label><label>Brand<select name="brand_id"><option value="">No brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id', $product->brand_id) == $brand->id)>{{ $brand->name }}</option>@endforeach</select></label><label>Price<input type="number" step="0.01" name="price" value="{{ old('price', $product->price) }}" required></label><label>Compare at price<input type="number" step="0.01" name="compare_at_price" value="{{ old('compare_at_price', $product->compare_at_price) }}"></label><label>Stock quantity<input type="number" name="stock_quantity" value="{{ old('stock_quantity', $product->stock_quantity ?? 0) }}"></label></div>
<div class="form-grid"><label>Arabic short description<textarea name="short_description_ar">{{ old('short_description_ar', $product->short_description_ar) }}</textarea></label><label>English short description<textarea name="short_description_en">{{ old('short_description_en', $product->short_description_en) }}</textarea></label><label>Arabic full description<textarea name="description_ar">{{ old('description_ar', $product->description_ar) }}</textarea></label><label>English full description<textarea name="description_en">{{ old('description_en', $product->description_en) }}</textarea></label></div>
<div class="form-grid"><label>Specifications JSON<textarea name="specifications_json" placeholder='{"Material":"Steel","Warranty":"12 months"}'>{{ old('specifications_json', $product->specifications ? json_encode($product->specifications, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) : '') }}</textarea></label><label>Main image<input type="file" name="main_image" accept="image/*"></label><label>Gallery images<input type="file" name="images[]" accept="image/*" multiple></label><label>Arabic meta title<input name="meta_title_ar" value="{{ old('meta_title_ar', $product->meta_title_ar) }}"></label><label>English meta title<input name="meta_title_en" value="{{ old('meta_title_en', $product->meta_title_en) }}"></label><label>Arabic meta description<textarea name="meta_description_ar">{{ old('meta_description_ar', $product->meta_description_ar) }}</textarea></label><label>English meta description<textarea name="meta_description_en">{{ old('meta_description_en', $product->meta_description_en) }}</textarea></label></div>
@if($product->exists && $product->images->isNotEmpty())<div class="admin-gallery">@foreach($product->images as $image)<div><img src="{{ $image->url() }}" alt=""><form method="POST" action="{{ route('admin.products.images.destroy', [$product, $image]) }}">@csrf @method('DELETE')<button type="submit">Remove</button></form></div>@endforeach</div>@endif
<div class="check-grid"><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? true))> Active</label><label><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $product->is_featured))> Featured</label></div>
<button class="btn-primary" type="submit">Save Product</button></form>
@endsection
